[".config/nu_scripts"]
    type = "archive"
    url = "https://github.com/nushell/nu_scripts/archive/refs/heads/main.zip"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".local/share/fonts"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/FiraMono.zip"
    exact = true