-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
local map = vim.keymap.set

map("n", "<leader>a", "", { desc = "+ai" })
map("n", "<leader>ac", "", { desc = "copilot" })
map("n", "<leader>act", function()
  vim.cmd("Copilot toggle")
end, { desc = "Toggle Copilot" })

map("n", "<leader>yf", "", { desc = "file paths" })
map("n", "<leader>yfp", function()
  vim.cmd("let @+ = expand('%:p')")
end, { desc = "copy file path" })
map("n", "<leader>yfpr", function()
  vim.cmd("let @+ = expand('%:p:r')")
end, { desc = "copy file path without extension" })
map("n", "<leader>yfn", function()
  vim.cmd("let @+ = expand('%:t')")
end, { desc = "copy file name" })
map("n", "<leader>yfnr", function()
  vim.cmd("let @+ = expand('%:t:r')")
end, { desc = "copy file name without extension" })
map("n", "<leader>yfph", function()
  vim.cmd("let @+ = expand('%:p:h')")
end, { desc = "copy file path without file name" })
map("n", "<leader>yfr", function()
  vim.cmd("let @+ = expand('%:.')")
end, { desc = "copy relative file path (cwd)" })
map("n", "<leader>yfe", function()
  vim.cmd("let @+ = expand('%:e')")
end, { desc = "copy file extension" })
map("n", "<leader>yffn", function()
  vim.cmd("let @+ = expand('%:t:r')")
end, { desc = "copy file name without extension" })
