#[working-copy]
#eof-conversion = "input"

[user]
name = "Dennie de Lange"
email = "621098+tkvw@users.noreply.github.com"

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/signing_keys/tkvw.github.com"

